[HWORKS-243] export audit logs
logicalclocks/logicalclocks.github.io pull request #136
Opened 2022-11-09 15:53 UTC by ErmiasG

2022-11-21 18:06 UTC, javierdlrm commented
I created a PR with some improvements https://github.com/ErmiasG/logicalclocks.github.io/pull/1

2022-11-21 18:07 UTC, javierdlrm requested changes
I opened a PR with some improvements [here](https://github.com/ErmiasG/logicalclocks.github.io/pull/1)

2022-11-23 08:13 UTC, robzor92 requested changes

2022-11-23 08:13 UTC, robzor92 commented on docs/admin/audit/audit-logs.md
> +    Hopsworks application needs to be reloaded for any changes to be applied. For doing that, go to the Payara admin panel (```https://<your-domain>:4848```), click on _Aplications_ on the side menu
```suggestion
    Hopsworks application needs to be reloaded for any changes to be applied. For doing that, go to the Payara admin panel (```https://<your-domain>:4848```), click on _Applications_ on the side menu and reload the _hopsworks-ear_ application.
```

2022-11-23 08:21 UTC, robzor92 approved these changes

2022-11-23 08:29 UTC, javierdlrm approved these changes

2022-11-23 08:30 UTC, merged