[FSTORE-379] Add documentation on how to share a feature store store and how to access it.
logicalclocks/logicalclocks.github.io pull request #138
Opened 2022-11-11 18:45 UTC by davitbzh

2022-11-15 09:02 UTC, SirOibaf requested changes

2022-11-15 09:02 UTC, SirOibaf commented on docs/user_guides/projects/share_and_access/sharing-a-feature-store.md
> +
I think we can add some text around this snippet. Something like: "To access features from a shared feature store you need to first retrieve the handle for the shared feature store. To retrieve the handle use the `get_feature_store()` method and provide the name of the shared feature store."

2022-11-15 09:02 UTC, SirOibaf commented on docs/user_guides/projects/share_and_access/sharing-a-feature-store.md
> +In this guide you learned how to share feature store between projects and join feature groups.
`how to share a feature store and how to join features from different feature stores.`

2022-11-16 09:20 UTC, bubriks commented on docs/user_guides/fs/sharing/sharing.md
> +shared_fg = shared_feature_store.get_or_create_feature_group(
From now on shared featurestores will be read-only, so if a feature group does not exist in the shared fs it will fail to be created.

2022-11-16 09:22 UTC, bubriks commented on docs/user_guides/projects/share_and_access/sharing-a-feature-store.md
> +In `Access rights` section select the permissions level that the project user members should have on the feature store and click Share.
yes, i guess now there would be no `Access rights` section (since we will have only read-only)

2022-11-21 11:14 UTC, moritzmeister commented
Tune back on the marketing part of the first chapter.

2022-11-21 13:11 UTC, SirOibaf commented
@davitbzh this is what I would write in the first section:
```
Hopsworks allows artifacts (e.g. feature groups, feature views) to be shared between projects.
There are two main use cases for sharing features between projects:

- If you have multiple teams working on the same Hopsworks deployment. Each team works within their own set of projects. If a team A wants to leverage features built by team B, they can do so by sharing the feature groups from a team A project to a team B project.

- By creating different projects for the different stages of development lifecycle (e.g. a dev project, a testing project and a production project), you can make sure that changes on the development project don't inpact the features in the production project. At the same time you might want to leverage production features to develop new models or additional features. In this case you can share the production feature store with the development feature store in read only mode.
```

2022-11-21 23:19 UTC, SirOibaf approved these changes

2022-11-21 23:19 UTC, SirOibaf approved these changes

2022-11-21 23:19 UTC, merged