change on On-Premise page
logicalclocks/logicalclocks.github.io pull request #216
Opened 2023-02-22 09:11 UTC by MagicLex

Removed detailed insall and quick-start.

2023-02-22 10:14 UTC, jimdowling requested changes

2023-02-22 10:14 UTC, jimdowling commented on docs/setup_installation/on_prem/hopsworks_installer.md
> +## Minimum Requirements
## Minimum Requirements

 * Ubuntu, Centos or RHEL Linux supported.

2023-02-22 10:14 UTC, jimdowling commented on docs/setup_installation/on_prem/hopsworks_installer.md
> +Further details about the on-premise installation of Hopsworks:
remove this, no need for these details

2023-02-22 10:14 UTC, jimdowling commented on docs/setup_installation/on_prem/hopsworks_installer.md
> +* If a multi-node installation is possible;
remove all of these, no need for these details

2023-03-02 12:17 UTC, SirOibaf commented
Work moved here: https://github.com/logicalclocks/logicalclocks.github.io/pull/223

2023-03-02 12:17 UTC, closed without merging