[FSTORE-698] Write Hudi performance best practices guide
logicalclocks/logicalclocks.github.io pull request #220
Opened 2023-02-27 13:01 UTC by moritzmeister

2023-02-27 13:24 UTC, SirOibaf commented
Can you add:
```
---
description: blabla bla
---
```
at the beginning of the page to add the page description. See https://hopsworks.atlassian.net/browse/HWORKS-421

2023-02-27 13:30 UTC, moritzmeister commented
@SirOibaf jap sorry, I knew I forgot something. paid attention to not wrap the image in a link though ;)

2023-02-27 15:00 UTC, jimdowling requested changes
Mostly typos. 
But, maybe you should add something about row group sizes. 
You could say, for example, that they should be aligned with the HopsFS block size (128MB, by default), as recommended here:

https://medium.com/swlh/insights-into-parquet-storage-ac7e46b94ffe#:~:text=Row%20Group%20%3A%20It%20is%20a,to%20the%20HDFS%20block%20size.&text=Page%3A%20Column%20chunks%20are%20divided%20up%20into%20pages.


Write something like. 
Unless you change your Hopsworks configuration to change the default HopsFS block size, then you won't need to worry about configuring the row group size.


Note: clients can read in parallel from different row groups in a parquet file, hence why it is important for configuration.

2023-02-27 16:22 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +    In practice that means the shuffle parallelism should be set equal to the number of feature group partitions being contained in the inserted dataframe.
I am always unsure, in pandas it's Dataframe, in spark it's DataFrame

2023-02-27 20:50 UTC, tdoehmen commented on docs/user_guides/fs/feature_group/create.md
> +    We recommend having shuffle parallelism `hoodie.[insert|upsert|bulkinsert].shuffle.parallelism` such that its at least input_data_size/500MB.
I wonder how this interacts with the `write.parquet.max.file.size` property (https://hudi.apache.org/docs/configurations/#writeparquetmaxfilesize)

2023-03-01 13:02 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +2. Parquet file size within a feature group partition
But that's not something you can control in hudi? so not really worth adding in this list I think?

2023-03-01 13:15 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +For Python environments, the stream pipeline is enabled by default, and this is the recommended way of writing to a feature group from
yeah, markdown doesn't really care about line breaks in the source file, so sometimes I just add a line break to make it more readable for us. But it doesn't affect the final html.

2023-03-01 13:15 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +When using the streaming API, the data will be written to the online storage (if `online_enabled=True`) on the shortest path. However, you can control when the sync to
changed it simply to "will be written directly to the online storage..."

2023-03-01 13:16 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +At the same time, Spark and Hudi tend to overpartition writes, slowing down the write.
tried to make it more clear, let me know what you think

2023-03-01 13:16 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +3. Backfilling of feature group partitions
see comment above

2023-03-01 13:16 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +    An event time column which is too granular, such as a timestamp, shouldn't be used as partition key.
tried to clarify with an example

2023-03-01 13:17 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
> +    In practice that means the shuffle parallelism should be set equal to the number of feature group partitions being contained in the inserted dataframe.
so when I am not referring to the concept of a dataframe in a specific framework I tend to write just "dataframe"

2023-03-01 13:17 UTC, moritzmeister commented on docs/user_guides/fs/feature_group/create.md
>  The snippet above only created the metadata object on the Python interpreter running the code. To register the feature group metadata and to save the feature data with Hopsworks, you should invoke th
thanks, this was old docs, fixed it.

2023-03-01 13:44 UTC, jimdowling approved these changes

2023-03-01 14:56 UTC, jimdowling commented on docs/user_guides/fs/feature_group/create.md
> +2. Parquet file size within a feature group partition
If you can't control it in Hudi, then leave it out.

2023-03-01 15:02 UTC, merged