CLOUD-435: Updated docs for Managed RonDB: Online Reconfiguration
logicalclocks/logicalclocks.github.io pull request #276
Opened 2023-05-30 17:57 UTC by mronstro

2023-06-02 18:18 UTC, smkniazi approved these changes

2023-06-08 11:39 UTC, maismail requested changes

2023-06-19 10:28 UTC, mronstro commented on docs/setup_installation/common/rondb.md
> +Local storage is used for offline storage of recovery data, and requires a disk of at least 40 GiB plus 1.8 times the memory size of the data node VM. RonDB does support on-disk columns that can be u
Agree on removing it from docs.

2023-06-19 10:28 UTC, mronstro commented on docs/setup_installation/common/rondb.md
> +Thus reconfiguring of the Storage Layer is mainly intended to meet long-term needs of the business in terms of
ok, will add

2023-06-19 10:31 UTC, mronstro commented on docs/assets/images/setup_installation/managed/common/rondb/reconfig_console_deactivate.png
Agree, but the work required for the change isn't worth the effort. Instead I will take it into account when updating the docs for Reconciliation which should not be that far away, fairly soon after vacations.

2023-06-20 13:32 UTC, maismail requested changes

2023-06-20 13:32 UTC, maismail commented on docs/setup_installation/common/rondb.md
> +
no need for this header
```suggestion
```

2023-08-03 14:31 UTC, maismail approved these changes

2023-08-03 14:34 UTC, merged