[FSTORE-1008] enable interacting with java client to hopsworks
logicalclocks/logicalclocks.github.io pull request #344
Opened 2024-01-30 17:23 UTC by davitbzh

2025-01-23 13:29 UTC, bubriks requested changes

2025-01-23 13:29 UTC, bubriks commented on docs/user_guides/fs/compute_engines.md
> +=======
bad merge

2025-01-23 13:29 UTC, bubriks commented on docs/user_guides/fs/compute_engines.md
> +<<<<<<< HEAD
bad merge

2025-01-26 18:13 UTC, davitbzh commented on docs/user_guides/fs/compute_engines.md
> +=======
thanks. good catch

2025-01-26 18:14 UTC, davitbzh commented on docs/user_guides/fs/compute_engines.md
> +<<<<<<< HEAD
fixed

2025-01-27 08:51 UTC, bubriks approved these changes

2025-01-27 08:51 UTC, bubriks commented on docs/user_guides/fs/compute_engines.md
> +It is also possible to interact to Hopsworks feature store using  pure Java environments without dependencies on Spark, Flink or Beam.
```suggestion
It is also possible to interact to Hopsworks feature store using pure Java environments without dependencies on Spark, Flink or Beam.
```

2025-06-10 08:44 UTC, SirOibaf approved these changes

2025-06-10 08:45 UTC, merged