[FSTORE-1418] Add embeding_index to fg creation guide
logicalclocks/logicalclocks.github.io pull request #388
Opened 2024-05-30 12:01 UTC by kennethmhc

2024-05-31 07:14 UTC, bubriks requested changes

2024-05-31 07:14 UTC, bubriks commented on docs/user_guides/fs/vector_similarity_search.md
> +Then, add one or more embedding features to the index. Name and dimension of the embedding features are required for identifying which features should be indexed for k-nearest neighbor (KNN) search.
```suggestion
Then, add one or more embedding features to the index. Name and dimension of the embedding features are required for identifying which features should be indexed for k-nearest neighbor (KNN) search. In this example, we get the dimension of the embedding by taking the length of the value of the `embedding_heading` column in the first row of the dataframe `df`. Optionally, you can specify the similarity function among `l2_norm`, `cosine`, and `dot_product`. Refer to [add_embedding](https://docs.hopsworks.ai/feature-store-api/{{{ hopsworks_version }}}/generated/api/embedding_index_api/#add_embedding) for the full list of arguments.
```

2024-05-31 07:25 UTC, kennethmhc commented
@bubriks applied the suggestion

2024-05-31 07:56 UTC, bubriks approved these changes

2024-05-31 09:02 UTC, merged

2024-06-17 11:41 UTC, kennethmhc reviewed
comment about version and a suggestion