updated tutotials
logicalclocks/logicalclocks.github.io pull request #39
Opened 2022-07-22 10:10 UTC by davitbzh

2022-07-22 10:19 UTC, MagicLex commented on docs/getting_started/quickstart.ipynb
> +    "**Note:** deployments for scikit-learn without Kserve require a predictor scrip. For details please refer to [Hopsworks documentation](https://docs.hopsworks.ai/latest/user_guides/mlops/serving/
"**Note:** deployments for scikit-learn without Kserve requires a predictor script. For details please refer to [Hopsworks documentation](https://docs.hopsworks.ai/latest/user_guides/mlops/serving/predictor/#step-2-optional-implement-predictor-script).  "

2022-07-22 11:34 UTC, MagicLex approved these changes

2022-07-25 07:43 UTC, moritzmeister submitted a review, later dismissed

2022-07-25 07:54 UTC, moritzmeister requested changes
I purposefully removed all the <span> etc from the notebooks, so they get displayed properly in the docs. When I tested it, these html parts didn't change anything. Why are you adding them back?

Also you are removing the "Open in Colab" buttons.

2022-07-25 07:54 UTC, moritzmeister commented on docs/tutorials/fraud_online/1_feature_groups.ipynb
> +    "# <span style=\"font-width:bold; font-size: 3rem; color:#1EB182;\"><img src=\"../images/icon102.png\" width=\"38px\"></img> **Hopsworks Feature Store** </span><span style=\"font-width:bold; font
Pretty sure this won't work. The image doesn't exist here. Also why all this HTML?

2022-07-25 07:54 UTC, moritzmeister commented on docs/tutorials/fraud_online/1_feature_groups.ipynb
> +    "## **🗒️ This notebook is divided in 3 sections:** \n",
The stars are redundant, they don't do anything if it's already a title.

2022-07-25 07:54 UTC, moritzmeister commented on docs/tutorials/fraud_online/1_feature_groups.ipynb
> +    "The objective of this tutorial is to demonstrate how to work with the **Hopworks Feature Store**  for batch data with a goal of training and deploying a model that can predict fraudulent transac
Pretty sure the span doesn't do anything.

2022-07-25 07:54 UTC, moritzmeister commented on docs/tutorials/fraud_online/2_feature_view_creation.ipynb
> -    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/logicalclocks/hopsworks-tutorials/blob/master/fraud_online/2_feature_view_cr
Why are you removing the Open in Colab buttons?

2022-07-26 09:50 UTC, moritzmeister commented
Added automation to pull notebooks automatically from hopsworks-tutorials

2022-07-26 09:50 UTC, closed without merging