[FSTORE-1442] Extend CDC notifications to include the project name
logicalclocks/logicalclocks.github.io pull request #393
Opened 2024-07-02 11:57 UTC by bubriks

2024-07-02 12:36 UTC, SirOibaf requested changes

2024-07-02 12:36 UTC, SirOibaf commented on docs/user_guides/fs/feature_group/notification.md
> +  "projectName":"project_name",  # name of the project used for data ingestion
I would change these to say that this is the project the feature group belongs to.

2024-07-02 12:36 UTC, SirOibaf commented on docs/user_guides/fs/feature_group/notification.md
> +  "projectName":"project_name",  # name of the project used for data ingestion
Same for the project id

2024-07-02 12:44 UTC, SirOibaf approved these changes

2024-07-30 20:25 UTC, jimdowling commented
@bubriks  - can you merge?

2024-07-30 20:26 UTC, merged