Spelling and phrasing improvements
logicalclocks/logicalclocks.github.io pull request #48
Opened 2022-07-28 12:37 UTC by robzor92

2022-07-28 12:47 UTC, moritzmeister requested changes

2022-07-28 12:47 UTC, moritzmeister commented on docs/concepts/projects/search.md
>  A keyword is a single user-defined word attached to a ML asset. Keywords can be used to help it make it easier to find ML assets or understand the context in which they should be used (for example, *
```suggestion
A keyword is a single user-defined word attached to an ML asset. Keywords can be used to help it make it easier to find ML assets or understand the context in which they should be used (for example, *PII* could be used to indicate that the ML asset is based on personally identifiable information.
```

2022-07-28 12:47 UTC, moritzmeister commented on docs/concepts/projects/storage.md
> +However, it is often desirable to share assets between projects, with read-only, read/write privileges, and to restrict the privileges to specific role (e.g., Data Owners) in the target project. In H
```suggestion
However, it is often desirable to share assets between projects, with read-only, read/write privileges, and to restrict the privileges to specific role (e.g., Data Owners) in the target project. In Hopsworks, you can explicitly share assets between projects without copying the assets. Sharing is managed by ACLs in Hopsworks, see example below:
```

2022-08-02 09:16 UTC, davitbzh approved these changes

2022-08-02 09:33 UTC, moritzmeister approved these changes

2022-08-02 09:33 UTC, merged