[FSTORE-36] Update val_size
logicalclocks/logicalclocks.github.io pull request #83
Opened 2022-09-19 16:45 UTC by kennethmhc

2022-09-20 12:53 UTC, jimdowling approved these changes

2022-09-20 19:34 UTC, SirOibaf requested changes
@kennethmhc - Beside the one I pointed out, can you make sure we don't have other `splits` left?

2022-09-20 19:34 UTC, SirOibaf commented on docs/user_guides/fs/feature_view/training-data.md
> +X_train, X_val, X_test, y_train, y_val, y_test = feature_view.train_validation_test_splits(validation_size=0.3, test_size=0.2)
The method name here is still wrong, it's `train_validation_test_split` without the (s)

2022-09-20 19:34 UTC, SirOibaf commented on docs/user_guides/fs/feature_view/training-data.md
>  version, job = feature_view.create_train_validation_test_splits(
Same comment on the method name.

2022-09-21 07:47 UTC, kennethmhc commented
@SirOibaf I made a search in logicalclocks org, cannot find any more.

2022-09-21 07:48 UTC, SirOibaf approved these changes

2022-09-26 06:49 UTC, jimdowling approved these changes

2022-09-27 08:53 UTC, merged